// Criteria Adapter Protocol v2.
//
// WS03 cutover: criteria/v1/adapter_plugin.proto was deleted; this file is
// now the sole wire contract for all adapter binaries (copilot, mcp, noop,
// shell-builtin, and third-party adapters). Any adapter previously built
// against v1 must be recompiled against these bindings.
//
// The Permissions RPC is a bidirectional stream: the HOST (gRPC client) sends
// PermissionEvent messages (request=allow, cancel=deny) and the ADAPTER (gRPC
// server) sends PermissionDecision acknowledgments back. Adapters that embed
// sdk/adapterhost.UnimplementedPermissions receive post-hoc enforcement
// (outcome override to needs_review on denial); adapters that implement
// Permissions themselves (e.g. copilot) get blocking enforcement so the tool
// never runs when denied.
//
// See docs/adapters.md for the feature roadmap and well-known event_kind registry.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: criteria/v2/adapter.proto

package criteriav2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chunk is the framing envelope for large payload fields on server-streaming
// RPCs (Execute, Log).  Within WS02, chunking applies only to
// AdapterEvent.payload_json, LogEvent.line, and ExecuteResult.outputs_json.
// seq is zero-based; final is true on the last chunk.
//
// When chunk is non-nil on a payload-bearing message, the typed payload field
// (payload, outputs) is nil; the raw bytes are carried in the corresponding
// *_json field instead.  Receivers concatenate *_json bytes in seq order and
// then unmarshal the result back to the typed form.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Final         bool                   `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Chunk) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Chunk) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

// Heartbeat is sent on every server-stream when no other traffic is flowing.
// Server streams send one every 30 s; two missed heartbeats (~60 s) trigger
// the crash-recovery policy.  SDKs provide a heartbeat helper so adapter
// authors do not need to manage timers.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamName    string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// ConfigFieldProto describes a single field in an adapter schema.
type ConfigFieldProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "string" | "number" | "bool" | "boolean" (alias for "bool") | "list_string"
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultStr    string                 `protobuf:"bytes,4,opt,name=default_str,json=defaultStr,proto3" json:"default_str,omitempty"`
	Sensitive     bool                   `protobuf:"varint,5,opt,name=sensitive,proto3" json:"sensitive,omitempty"` // marks the field as a taint-source for downstream tools
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldProto) Reset() {
	*x = ConfigFieldProto{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldProto) ProtoMessage() {}

func (x *ConfigFieldProto) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldProto.ProtoReflect.Descriptor instead.
func (*ConfigFieldProto) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigFieldProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigFieldProto) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigFieldProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigFieldProto) GetDefaultStr() string {
	if x != nil {
		return x.DefaultStr
	}
	return ""
}

func (x *ConfigFieldProto) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

// AdapterSchemaProto holds a named set of config/input/output fields.
type AdapterSchemaProto struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Fields        map[string]*ConfigFieldProto `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterSchemaProto) Reset() {
	*x = AdapterSchemaProto{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterSchemaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterSchemaProto) ProtoMessage() {}

func (x *AdapterSchemaProto) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterSchemaProto.ProtoReflect.Descriptor instead.
func (*AdapterSchemaProto) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *AdapterSchemaProto) GetFields() map[string]*ConfigFieldProto {
	if x != nil {
		return x.Fields
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{4}
}

type InfoResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version                string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities           []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Platforms              []string               `protobuf:"bytes,5,rep,name=platforms,proto3" json:"platforms,omitempty"`
	SdkProtocolVersion     string                 `protobuf:"bytes,6,opt,name=sdk_protocol_version,json=sdkProtocolVersion,proto3" json:"sdk_protocol_version,omitempty"`
	SourceUrl              string                 `protobuf:"bytes,7,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	ConfigSchema           *AdapterSchemaProto    `protobuf:"bytes,8,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	InputSchema            *AdapterSchemaProto    `protobuf:"bytes,9,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema           *AdapterSchemaProto    `protobuf:"bytes,10,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`                                             // NEW v2: schema for step outputs
	Secrets                map[string]string      `protobuf:"bytes,11,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // declared secret names → descriptions
	Permissions            []string               `protobuf:"bytes,12,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CompatibleEnvironments []string               `protobuf:"bytes,13,rep,name=compatible_environments,json=compatibleEnvironments,proto3" json:"compatible_environments,omitempty"`
	ContainerImage         string                 `protobuf:"bytes,14,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	// supported_features lists optional capabilities this adapter implements.
	// Well-known values: "pause", "resume", "snapshot", "restore", "inspect".
	// The host gates UI and behavior on this list; unknown values are ignored
	// for forward-compatibility.  Empty = none of the optional features.
	SupportedFeatures []string `protobuf:"bytes,15,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"` // NEW v2 (D76)
	// max_chunk_bytes is the maximum payload the adapter accepts in a single
	// message field before requiring chunked framing.  0 = use default (4 MiB).
	// The host uses min(host_max, adapter_max) when chunking outbound payloads.
	MaxChunkBytes uint32 `protobuf:"varint,16,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"` // NEW v2 (D78)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *InfoResponse) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *InfoResponse) GetSdkProtocolVersion() string {
	if x != nil {
		return x.SdkProtocolVersion
	}
	return ""
}

func (x *InfoResponse) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *InfoResponse) GetConfigSchema() *AdapterSchemaProto {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *InfoResponse) GetInputSchema() *AdapterSchemaProto {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *InfoResponse) GetOutputSchema() *AdapterSchemaProto {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *InfoResponse) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *InfoResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *InfoResponse) GetCompatibleEnvironments() []string {
	if x != nil {
		return x.CompatibleEnvironments
	}
	return nil
}

func (x *InfoResponse) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *InfoResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *InfoResponse) GetMaxChunkBytes() uint32 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

type OpenSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Config    map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// secrets carries secret values for this session.  Redaction-aware log
	// pipelines MUST mask or refuse to log any field annotated sensitive.
	Secrets         map[string]string `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllowedOutcomes []string          `protobuf:"bytes,4,rep,name=allowed_outcomes,json=allowedOutcomes,proto3" json:"allowed_outcomes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *OpenSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenSessionRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *OpenSessionRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *OpenSessionRequest) GetAllowedOutcomes() []string {
	if x != nil {
		return x.AllowedOutcomes
	}
	return nil
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{7}
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{8}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{9}
}

type ExecuteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepName        string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Input           map[string]string      `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SecretInputs    map[string]string      `protobuf:"bytes,4,rep,name=secret_inputs,json=secretInputs,proto3" json:"secret_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllowedOutcomes []string               `protobuf:"bytes,5,rep,name=allowed_outcomes,json=allowedOutcomes,proto3" json:"allowed_outcomes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecuteRequest) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetSecretInputs() map[string]string {
	if x != nil {
		return x.SecretInputs
	}
	return nil
}

func (x *ExecuteRequest) GetAllowedOutcomes() []string {
	if x != nil {
		return x.AllowedOutcomes
	}
	return nil
}

// AdapterEvent is a typed semantic event emitted by the adapter.
// event_kind is a dot-separated identifier; well-known values are registered
// in docs/adapters.md (WS39).  Unknown kinds are forwarded unchanged.
//
// Chunked encoding: when chunk is non-nil, payload is nil and payload_json
// carries the raw JSON bytes of this fragment.  Reassemble payload_json bytes
// in Chunk.seq order and unmarshal the result to google.protobuf.Struct.
type AdapterEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventKind string                 `protobuf:"bytes,1,opt,name=event_kind,json=eventKind,proto3" json:"event_kind,omitempty"`
	// payload is set when chunk == nil (non-chunked or single-message payload).
	Payload   *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	EmittedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	Chunk     *Chunk                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// payload_json carries the JSON-encoded bytes of a payload fragment when
	// chunk is non-nil.  Collect all fragments in Chunk.seq order, concatenate,
	// then unmarshal to google.protobuf.Struct.
	PayloadJson   []byte `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterEvent) Reset() {
	*x = AdapterEvent{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterEvent) ProtoMessage() {}

func (x *AdapterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterEvent.ProtoReflect.Descriptor instead.
func (*AdapterEvent) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{11}
}

func (x *AdapterEvent) GetEventKind() string {
	if x != nil {
		return x.EventKind
	}
	return ""
}

func (x *AdapterEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AdapterEvent) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *AdapterEvent) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *AdapterEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

// ToolInvocation is emitted when the adapter invokes an external tool.
type ToolInvocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Args          *structpb.Struct       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	InvokedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=invoked_at,json=invokedAt,proto3" json:"invoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInvocation) Reset() {
	*x = ToolInvocation{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInvocation) ProtoMessage() {}

func (x *ToolInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInvocation.ProtoReflect.Descriptor instead.
func (*ToolInvocation) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{12}
}

func (x *ToolInvocation) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolInvocation) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolInvocation) GetInvokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvokedAt
	}
	return nil
}

type ExecuteResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Outcome string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// outputs is set when chunk == nil (non-chunked or single-message payload).
	Outputs map[string]string `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Chunk   *Chunk            `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// outputs_json carries the JSON-encoded bytes of an outputs map fragment when
	// chunk is non-nil.  Collect all fragments in Chunk.seq order, concatenate,
	// then unmarshal to map<string,string>.
	OutputsJson   []byte `protobuf:"bytes,4,opt,name=outputs_json,json=outputsJson,proto3" json:"outputs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ExecuteResult) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecuteResult) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ExecuteResult) GetOutputsJson() []byte {
	if x != nil {
		return x.OutputsJson
	}
	return nil
}

// ExecuteEvent is the stream message for the Execute RPC.
// Log lines are NOT included here; they flow through the Log RPC.
type ExecuteEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteEvent_Adapter
	//	*ExecuteEvent_Tool
	//	*ExecuteEvent_Result
	//	*ExecuteEvent_Heartbeat
	Event         isExecuteEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteEvent) GetEvent() isExecuteEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteEvent) GetAdapter() *AdapterEvent {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Adapter); ok {
			return x.Adapter
		}
	}
	return nil
}

func (x *ExecuteEvent) GetTool() *ToolInvocation {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *ExecuteEvent) GetResult() *ExecuteResult {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isExecuteEvent_Event interface {
	isExecuteEvent_Event()
}

type ExecuteEvent_Adapter struct {
	Adapter *AdapterEvent `protobuf:"bytes,1,opt,name=adapter,proto3,oneof"`
}

type ExecuteEvent_Tool struct {
	Tool *ToolInvocation `protobuf:"bytes,2,opt,name=tool,proto3,oneof"`
}

type ExecuteEvent_Result struct {
	Result *ExecuteResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type ExecuteEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ExecuteEvent_Adapter) isExecuteEvent_Event() {}

func (*ExecuteEvent_Tool) isExecuteEvent_Event() {}

func (*ExecuteEvent_Result) isExecuteEvent_Event() {}

func (*ExecuteEvent_Heartbeat) isExecuteEvent_Event() {}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{15}
}

func (x *LogRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

// LogEvent is the stream message for the Log RPC.
//
// stream_name must match ^[a-z][a-z0-9_-]{0,31}$.
// Well-known values: "stdout", "stderr", "agent".
// Extensions like "tool", "trace", "metric" are accepted without a proto bump.
// chunk is non-nil when this message carries a partial payload; all chunks for
// a given stream_name must be reassembled in seq order before consuming line.
// line is raw bytes so it is safe to split at any byte boundary without
// breaking UTF-8; callers that need a string must decode after reassembly.
type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	StreamName    string                 `protobuf:"bytes,3,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	Line          []byte                 `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Heartbeat     *Heartbeat             `protobuf:"bytes,6,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Chunk         *Chunk                 `protobuf:"bytes,7,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{16}
}

func (x *LogEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *LogEvent) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *LogEvent) GetLine() []byte {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *LogEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *LogEvent) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// PermissionRequest is sent by the adapter to request permission for a tool call.
// args_digest = sha256(canonical_json(args)) per the JCS / RFC 8785 algorithm
// (see internal/adapter/audit/canonical.go).
type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	ArgsDigest    string                 `protobuf:"bytes,3,opt,name=args_digest,json=argsDigest,proto3" json:"args_digest,omitempty"` // sha256(canonical_json(args))
	ArgsPreview   string                 `protobuf:"bytes,4,opt,name=args_preview,json=argsPreview,proto3" json:"args_preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{17}
}

func (x *PermissionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PermissionRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *PermissionRequest) GetArgsDigest() string {
	if x != nil {
		return x.ArgsDigest
	}
	return ""
}

func (x *PermissionRequest) GetArgsPreview() string {
	if x != nil {
		return x.ArgsPreview
	}
	return ""
}

// PermissionCancel carries a deny decision from the HOST to the ADAPTER on the
// Permissions stream. When the host denies a tool request, it sends a
// PermissionEvent with cancel set; the adapter unblocks the pending request
// and returns Denied to the Copilot SDK so the tool does not run.
// reason is optional human-readable text (e.g. "no matching allow_tools entry").
type PermissionCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionCancel) Reset() {
	*x = PermissionCancel{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionCancel) ProtoMessage() {}

func (x *PermissionCancel) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionCancel.ProtoReflect.Descriptor instead.
func (*PermissionCancel) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{18}
}

func (x *PermissionCancel) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PermissionCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PermissionEvent is the client-to-server message on the Permissions stream.
type PermissionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*PermissionEvent_Request
	//	*PermissionEvent_Cancel
	Event         isPermissionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionEvent) Reset() {
	*x = PermissionEvent{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionEvent) ProtoMessage() {}

func (x *PermissionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionEvent.ProtoReflect.Descriptor instead.
func (*PermissionEvent) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{19}
}

func (x *PermissionEvent) GetEvent() isPermissionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PermissionEvent) GetRequest() *PermissionRequest {
	if x != nil {
		if x, ok := x.Event.(*PermissionEvent_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *PermissionEvent) GetCancel() *PermissionCancel {
	if x != nil {
		if x, ok := x.Event.(*PermissionEvent_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isPermissionEvent_Event interface {
	isPermissionEvent_Event()
}

type PermissionEvent_Request struct {
	Request *PermissionRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type PermissionEvent_Cancel struct {
	Cancel *PermissionCancel `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

func (*PermissionEvent_Request) isPermissionEvent_Event() {}

func (*PermissionEvent_Cancel) isPermissionEvent_Event() {}

// PermissionDecision is the server-to-client message on the Permissions stream.
// The host answers requests in any order; multiple requests may be in flight.
// heartbeat is non-nil when this message is a liveness ping with no decision.
type PermissionDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"` // "allow" | "deny"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Heartbeat     *Heartbeat             `protobuf:"bytes,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDecision) Reset() {
	*x = PermissionDecision{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDecision) ProtoMessage() {}

func (x *PermissionDecision) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDecision.ProtoReflect.Descriptor instead.
func (*PermissionDecision) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{20}
}

func (x *PermissionDecision) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PermissionDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *PermissionDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PermissionDecision) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{21}
}

func (x *PauseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResponse) Reset() {
	*x = PauseResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResponse) ProtoMessage() {}

func (x *PauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResponse.ProtoReflect.Descriptor instead.
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{22}
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{23}
}

func (x *ResumeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{24}
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{25}
}

func (x *SnapshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []byte                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{26}
}

func (x *SnapshotResponse) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SnapshotResponse) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         []byte                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{27}
}

func (x *RestoreRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RestoreRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RestoreRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{28}
}

// SnapshotVersionMismatch is returned as a gRPC/Connect error detail when a
// Restore request specifies a schema_version the adapter cannot read.
// The host surfaces this as: "snapshot taken at v<have>, adapter speaks v<want>
// only — refusing to restore".
type SnapshotVersionMismatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Have          uint32                 `protobuf:"varint,1,opt,name=have,proto3" json:"have,omitempty"` // schema_version from the RestoreRequest
	Want          uint32                 `protobuf:"varint,2,opt,name=want,proto3" json:"want,omitempty"` // schema_version this adapter can handle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotVersionMismatch) Reset() {
	*x = SnapshotVersionMismatch{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotVersionMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotVersionMismatch) ProtoMessage() {}

func (x *SnapshotVersionMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotVersionMismatch.ProtoReflect.Descriptor instead.
func (*SnapshotVersionMismatch) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{29}
}

func (x *SnapshotVersionMismatch) GetHave() uint32 {
	if x != nil {
		return x.Have
	}
	return 0
}

func (x *SnapshotVersionMismatch) GetWant() uint32 {
	if x != nil {
		return x.Want
	}
	return 0
}

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{30}
}

func (x *InspectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// InspectField is an adapter-defined structured field for operator UIs.
type InspectField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // human-friendly label for UIs
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectField) Reset() {
	*x = InspectField{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectField) ProtoMessage() {}

func (x *InspectField) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectField.ProtoReflect.Descriptor instead.
func (*InspectField) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{31}
}

func (x *InspectField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InspectField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *InspectField) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type InspectResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CurrentStep            string                 `protobuf:"bytes,1,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	PendingPermissionCount uint32                 `protobuf:"varint,2,opt,name=pending_permission_count,json=pendingPermissionCount,proto3" json:"pending_permission_count,omitempty"`
	LastActivityAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	Fields                 []*InspectField        `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Extra                  *structpb.Struct       `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"` // freeform escape hatch
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_criteria_v2_adapter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteria_v2_adapter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_criteria_v2_adapter_proto_rawDescGZIP(), []int{32}
}

func (x *InspectResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *InspectResponse) GetPendingPermissionCount() uint32 {
	if x != nil {
		return x.PendingPermissionCount
	}
	return 0
}

func (x *InspectResponse) GetLastActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAt
	}
	return nil
}

func (x *InspectResponse) GetFields() []*InspectField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *InspectResponse) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_criteria_v2_adapter_proto protoreflect.FileDescriptor

const file_criteria_v2_adapter_proto_rawDesc = "" +
	"\n" +
	"\x19criteria/v2/adapter.proto\x12\vcriteria.v2\x1a\x19criteria/v2/options.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x05Chunk\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05finalJ\x05\bd\x10\xe8\a\"h\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAtJ\x05\bd\x10\xe8\a\"\xaa\x01\n" +
	"\x10ConfigFieldProto\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vdefault_str\x18\x04 \x01(\tR\n" +
	"defaultStr\x12\x1c\n" +
	"\tsensitive\x18\x05 \x01(\bR\tsensitiveJ\x05\bd\x10\xe8\a\"\xba\x01\n" +
	"\x12AdapterSchemaProto\x12C\n" +
	"\x06fields\x18\x01 \x03(\v2+.criteria.v2.AdapterSchemaProto.FieldsEntryR\x06fields\x1aX\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.criteria.v2.ConfigFieldProtoR\x05value:\x028\x01J\x05\bd\x10\xe8\a\"\x14\n" +
	"\vInfoRequestJ\x05\bd\x10\xe8\a\"\xa1\x06\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1c\n" +
	"\tplatforms\x18\x05 \x03(\tR\tplatforms\x120\n" +
	"\x14sdk_protocol_version\x18\x06 \x01(\tR\x12sdkProtocolVersion\x12\x1d\n" +
	"\n" +
	"source_url\x18\a \x01(\tR\tsourceUrl\x12D\n" +
	"\rconfig_schema\x18\b \x01(\v2\x1f.criteria.v2.AdapterSchemaProtoR\fconfigSchema\x12B\n" +
	"\finput_schema\x18\t \x01(\v2\x1f.criteria.v2.AdapterSchemaProtoR\vinputSchema\x12D\n" +
	"\routput_schema\x18\n" +
	" \x01(\v2\x1f.criteria.v2.AdapterSchemaProtoR\foutputSchema\x12@\n" +
	"\asecrets\x18\v \x03(\v2&.criteria.v2.InfoResponse.SecretsEntryR\asecrets\x12 \n" +
	"\vpermissions\x18\f \x03(\tR\vpermissions\x127\n" +
	"\x17compatible_environments\x18\r \x03(\tR\x16compatibleEnvironments\x12'\n" +
	"\x0fcontainer_image\x18\x0e \x01(\tR\x0econtainerImage\x12-\n" +
	"\x12supported_features\x18\x0f \x03(\tR\x11supportedFeatures\x12&\n" +
	"\x0fmax_chunk_bytes\x18\x10 \x01(\rR\rmaxChunkBytes\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x05\bd\x10\xe8\a\"\x8a\x03\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12C\n" +
	"\x06config\x18\x02 \x03(\v2+.criteria.v2.OpenSessionRequest.ConfigEntryR\x06config\x12L\n" +
	"\asecrets\x18\x03 \x03(\v2,.criteria.v2.OpenSessionRequest.SecretsEntryB\x04\x80\x97\"\x01R\asecrets\x12)\n" +
	"\x10allowed_outcomes\x18\x04 \x03(\tR\x0fallowedOutcomes\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\a\x10\bJ\x05\bd\x10\xe8\aR\x13environment_context\"\x1c\n" +
	"\x13OpenSessionResponseJ\x05\bd\x10\xe8\a\";\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdJ\x05\bd\x10\xe8\a\"\x1d\n" +
	"\x14CloseSessionResponseJ\x05\bd\x10\xe8\a\"\x91\x03\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12<\n" +
	"\x05input\x18\x03 \x03(\v2&.criteria.v2.ExecuteRequest.InputEntryR\x05input\x12X\n" +
	"\rsecret_inputs\x18\x04 \x03(\v2-.criteria.v2.ExecuteRequest.SecretInputsEntryB\x04\x80\x97\"\x01R\fsecretInputs\x12)\n" +
	"\x10allowed_outcomes\x18\x05 \x03(\tR\x0fallowedOutcomes\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11SecretInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x05\bd\x10\xe8\a\"\xef\x01\n" +
	"\fAdapterEvent\x12\x1d\n" +
	"\n" +
	"event_kind\x18\x01 \x01(\tR\teventKind\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\x129\n" +
	"\n" +
	"emitted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12(\n" +
	"\x05chunk\x18\x04 \x01(\v2\x12.criteria.v2.ChunkR\x05chunk\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\fR\vpayloadJsonJ\x05\bd\x10\xe8\a\"\x9c\x01\n" +
	"\x0eToolInvocation\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\x129\n" +
	"\n" +
	"invoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tinvokedAtJ\x05\bd\x10\xe8\a\"\xfc\x01\n" +
	"\rExecuteResult\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12A\n" +
	"\aoutputs\x18\x02 \x03(\v2'.criteria.v2.ExecuteResult.OutputsEntryR\aoutputs\x12(\n" +
	"\x05chunk\x18\x03 \x01(\v2\x12.criteria.v2.ChunkR\x05chunk\x12!\n" +
	"\foutputs_json\x18\x04 \x01(\fR\voutputsJson\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x05\bd\x10\xe8\a\"\xf6\x01\n" +
	"\fExecuteEvent\x125\n" +
	"\aadapter\x18\x01 \x01(\v2\x19.criteria.v2.AdapterEventH\x00R\aadapter\x121\n" +
	"\x04tool\x18\x02 \x01(\v2\x1b.criteria.v2.ToolInvocationH\x00R\x04tool\x124\n" +
	"\x06result\x18\x03 \x01(\v2\x1a.criteria.v2.ExecuteResultH\x00R\x06result\x126\n" +
	"\theartbeat\x18\x04 \x01(\v2\x16.criteria.v2.HeartbeatH\x00R\theartbeatB\a\n" +
	"\x05eventJ\x05\bd\x10\xe8\a\"O\n" +
	"\n" +
	"LogRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepNameJ\x05\bd\x10\xe8\a\"\x9c\x02\n" +
	"\bLogEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x1f\n" +
	"\vstream_name\x18\x03 \x01(\tR\n" +
	"streamName\x12\x12\n" +
	"\x04line\x18\x04 \x01(\fR\x04line\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x124\n" +
	"\theartbeat\x18\x06 \x01(\v2\x16.criteria.v2.HeartbeatR\theartbeat\x12(\n" +
	"\x05chunk\x18\a \x01(\v2\x12.criteria.v2.ChunkR\x05chunkJ\x05\bd\x10\xe8\a\"\x9d\x01\n" +
	"\x11PermissionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1f\n" +
	"\vargs_digest\x18\x03 \x01(\tR\n" +
	"argsDigest\x12!\n" +
	"\fargs_preview\x18\x04 \x01(\tR\vargsPreviewJ\x04\b\x05\x10\x06J\x05\bd\x10\xe8\aR\x04args\"P\n" +
	"\x10PermissionCancel\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonJ\x05\bd\x10\xe8\a\"\x96\x01\n" +
	"\x0fPermissionEvent\x12:\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.criteria.v2.PermissionRequestH\x00R\arequest\x127\n" +
	"\x06cancel\x18\x02 \x01(\v2\x1d.criteria.v2.PermissionCancelH\x00R\x06cancelB\a\n" +
	"\x05eventJ\x05\bd\x10\xe8\a\"\xa4\x01\n" +
	"\x12PermissionDecision\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x16.criteria.v2.HeartbeatR\theartbeatJ\x05\bd\x10\xe8\a\"4\n" +
	"\fPauseRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdJ\x05\bd\x10\xe8\a\"\x16\n" +
	"\rPauseResponseJ\x05\bd\x10\xe8\a\"5\n" +
	"\rResumeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdJ\x05\bd\x10\xe8\a\"\x17\n" +
	"\x0eResumeResponseJ\x05\bd\x10\xe8\a\"7\n" +
	"\x0fSnapshotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdJ\x05\bd\x10\xe8\a\"\\\n" +
	"\x10SnapshotResponse\x12\x1a\n" +
	"\x05state\x18\x01 \x01(\fB\x04\x80\x97\"\x01R\x05state\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersionJ\x05\bd\x10\xe8\a\"y\n" +
	"\x0eRestoreRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\x05state\x18\x02 \x01(\fB\x04\x80\x97\"\x01R\x05state\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\rR\rschemaVersionJ\x05\bd\x10\xe8\a\"\x18\n" +
	"\x0fRestoreResponseJ\x05\bd\x10\xe8\a\"H\n" +
	"\x17SnapshotVersionMismatch\x12\x12\n" +
	"\x04have\x18\x01 \x01(\rR\x04have\x12\x12\n" +
	"\x04want\x18\x02 \x01(\rR\x04wantJ\x05\bd\x10\xe8\a\"6\n" +
	"\x0eInspectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdJ\x05\bd\x10\xe8\a\"k\n" +
	"\fInspectField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05valueJ\x05\bd\x10\xe8\a\"\x9d\x02\n" +
	"\x0fInspectResponse\x12!\n" +
	"\fcurrent_step\x18\x01 \x01(\tR\vcurrentStep\x128\n" +
	"\x18pending_permission_count\x18\x02 \x01(\rR\x16pendingPermissionCount\x12D\n" +
	"\x10last_activity_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastActivityAt\x121\n" +
	"\x06fields\x18\x04 \x03(\v2\x19.criteria.v2.InspectFieldR\x06fields\x12-\n" +
	"\x05extra\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05extraJ\x05\bd\x10\xe8\a2\x9c\x06\n" +
	"\x0eAdapterService\x12;\n" +
	"\x04Info\x12\x18.criteria.v2.InfoRequest\x1a\x19.criteria.v2.InfoResponse\x12P\n" +
	"\vOpenSession\x12\x1f.criteria.v2.OpenSessionRequest\x1a .criteria.v2.OpenSessionResponse\x12C\n" +
	"\aExecute\x12\x1b.criteria.v2.ExecuteRequest\x1a\x19.criteria.v2.ExecuteEvent0\x01\x127\n" +
	"\x03Log\x12\x17.criteria.v2.LogRequest\x1a\x15.criteria.v2.LogEvent0\x01\x12P\n" +
	"\vPermissions\x12\x1c.criteria.v2.PermissionEvent\x1a\x1f.criteria.v2.PermissionDecision(\x010\x01\x12>\n" +
	"\x05Pause\x12\x19.criteria.v2.PauseRequest\x1a\x1a.criteria.v2.PauseResponse\x12A\n" +
	"\x06Resume\x12\x1a.criteria.v2.ResumeRequest\x1a\x1b.criteria.v2.ResumeResponse\x12G\n" +
	"\bSnapshot\x12\x1c.criteria.v2.SnapshotRequest\x1a\x1d.criteria.v2.SnapshotResponse\x12D\n" +
	"\aRestore\x12\x1b.criteria.v2.RestoreRequest\x1a\x1c.criteria.v2.RestoreResponse\x12D\n" +
	"\aInspect\x12\x1b.criteria.v2.InspectRequest\x1a\x1c.criteria.v2.InspectResponse\x12S\n" +
	"\fCloseSession\x12 .criteria.v2.CloseSessionRequest\x1a!.criteria.v2.CloseSessionResponseB=Z;github.com/brokenbots/criteria/proto/criteria/v2;criteriav2b\x06proto3"

var (
	file_criteria_v2_adapter_proto_rawDescOnce sync.Once
	file_criteria_v2_adapter_proto_rawDescData []byte
)

func file_criteria_v2_adapter_proto_rawDescGZIP() []byte {
	file_criteria_v2_adapter_proto_rawDescOnce.Do(func() {
		file_criteria_v2_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteria_v2_adapter_proto_rawDesc), len(file_criteria_v2_adapter_proto_rawDesc)))
	})
	return file_criteria_v2_adapter_proto_rawDescData
}

var file_criteria_v2_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_criteria_v2_adapter_proto_goTypes = []any{
	(*Chunk)(nil),                   // 0: criteria.v2.Chunk
	(*Heartbeat)(nil),               // 1: criteria.v2.Heartbeat
	(*ConfigFieldProto)(nil),        // 2: criteria.v2.ConfigFieldProto
	(*AdapterSchemaProto)(nil),      // 3: criteria.v2.AdapterSchemaProto
	(*InfoRequest)(nil),             // 4: criteria.v2.InfoRequest
	(*InfoResponse)(nil),            // 5: criteria.v2.InfoResponse
	(*OpenSessionRequest)(nil),      // 6: criteria.v2.OpenSessionRequest
	(*OpenSessionResponse)(nil),     // 7: criteria.v2.OpenSessionResponse
	(*CloseSessionRequest)(nil),     // 8: criteria.v2.CloseSessionRequest
	(*CloseSessionResponse)(nil),    // 9: criteria.v2.CloseSessionResponse
	(*ExecuteRequest)(nil),          // 10: criteria.v2.ExecuteRequest
	(*AdapterEvent)(nil),            // 11: criteria.v2.AdapterEvent
	(*ToolInvocation)(nil),          // 12: criteria.v2.ToolInvocation
	(*ExecuteResult)(nil),           // 13: criteria.v2.ExecuteResult
	(*ExecuteEvent)(nil),            // 14: criteria.v2.ExecuteEvent
	(*LogRequest)(nil),              // 15: criteria.v2.LogRequest
	(*LogEvent)(nil),                // 16: criteria.v2.LogEvent
	(*PermissionRequest)(nil),       // 17: criteria.v2.PermissionRequest
	(*PermissionCancel)(nil),        // 18: criteria.v2.PermissionCancel
	(*PermissionEvent)(nil),         // 19: criteria.v2.PermissionEvent
	(*PermissionDecision)(nil),      // 20: criteria.v2.PermissionDecision
	(*PauseRequest)(nil),            // 21: criteria.v2.PauseRequest
	(*PauseResponse)(nil),           // 22: criteria.v2.PauseResponse
	(*ResumeRequest)(nil),           // 23: criteria.v2.ResumeRequest
	(*ResumeResponse)(nil),          // 24: criteria.v2.ResumeResponse
	(*SnapshotRequest)(nil),         // 25: criteria.v2.SnapshotRequest
	(*SnapshotResponse)(nil),        // 26: criteria.v2.SnapshotResponse
	(*RestoreRequest)(nil),          // 27: criteria.v2.RestoreRequest
	(*RestoreResponse)(nil),         // 28: criteria.v2.RestoreResponse
	(*SnapshotVersionMismatch)(nil), // 29: criteria.v2.SnapshotVersionMismatch
	(*InspectRequest)(nil),          // 30: criteria.v2.InspectRequest
	(*InspectField)(nil),            // 31: criteria.v2.InspectField
	(*InspectResponse)(nil),         // 32: criteria.v2.InspectResponse
	nil,                             // 33: criteria.v2.AdapterSchemaProto.FieldsEntry
	nil,                             // 34: criteria.v2.InfoResponse.SecretsEntry
	nil,                             // 35: criteria.v2.OpenSessionRequest.ConfigEntry
	nil,                             // 36: criteria.v2.OpenSessionRequest.SecretsEntry
	nil,                             // 37: criteria.v2.ExecuteRequest.InputEntry
	nil,                             // 38: criteria.v2.ExecuteRequest.SecretInputsEntry
	nil,                             // 39: criteria.v2.ExecuteResult.OutputsEntry
	(*timestamppb.Timestamp)(nil),   // 40: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 41: google.protobuf.Struct
	(*structpb.Value)(nil),          // 42: google.protobuf.Value
}
var file_criteria_v2_adapter_proto_depIdxs = []int32{
	40, // 0: criteria.v2.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	33, // 1: criteria.v2.AdapterSchemaProto.fields:type_name -> criteria.v2.AdapterSchemaProto.FieldsEntry
	3,  // 2: criteria.v2.InfoResponse.config_schema:type_name -> criteria.v2.AdapterSchemaProto
	3,  // 3: criteria.v2.InfoResponse.input_schema:type_name -> criteria.v2.AdapterSchemaProto
	3,  // 4: criteria.v2.InfoResponse.output_schema:type_name -> criteria.v2.AdapterSchemaProto
	34, // 5: criteria.v2.InfoResponse.secrets:type_name -> criteria.v2.InfoResponse.SecretsEntry
	35, // 6: criteria.v2.OpenSessionRequest.config:type_name -> criteria.v2.OpenSessionRequest.ConfigEntry
	36, // 7: criteria.v2.OpenSessionRequest.secrets:type_name -> criteria.v2.OpenSessionRequest.SecretsEntry
	37, // 8: criteria.v2.ExecuteRequest.input:type_name -> criteria.v2.ExecuteRequest.InputEntry
	38, // 9: criteria.v2.ExecuteRequest.secret_inputs:type_name -> criteria.v2.ExecuteRequest.SecretInputsEntry
	41, // 10: criteria.v2.AdapterEvent.payload:type_name -> google.protobuf.Struct
	40, // 11: criteria.v2.AdapterEvent.emitted_at:type_name -> google.protobuf.Timestamp
	0,  // 12: criteria.v2.AdapterEvent.chunk:type_name -> criteria.v2.Chunk
	41, // 13: criteria.v2.ToolInvocation.args:type_name -> google.protobuf.Struct
	40, // 14: criteria.v2.ToolInvocation.invoked_at:type_name -> google.protobuf.Timestamp
	39, // 15: criteria.v2.ExecuteResult.outputs:type_name -> criteria.v2.ExecuteResult.OutputsEntry
	0,  // 16: criteria.v2.ExecuteResult.chunk:type_name -> criteria.v2.Chunk
	11, // 17: criteria.v2.ExecuteEvent.adapter:type_name -> criteria.v2.AdapterEvent
	12, // 18: criteria.v2.ExecuteEvent.tool:type_name -> criteria.v2.ToolInvocation
	13, // 19: criteria.v2.ExecuteEvent.result:type_name -> criteria.v2.ExecuteResult
	1,  // 20: criteria.v2.ExecuteEvent.heartbeat:type_name -> criteria.v2.Heartbeat
	40, // 21: criteria.v2.LogEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 22: criteria.v2.LogEvent.heartbeat:type_name -> criteria.v2.Heartbeat
	0,  // 23: criteria.v2.LogEvent.chunk:type_name -> criteria.v2.Chunk
	17, // 24: criteria.v2.PermissionEvent.request:type_name -> criteria.v2.PermissionRequest
	18, // 25: criteria.v2.PermissionEvent.cancel:type_name -> criteria.v2.PermissionCancel
	1,  // 26: criteria.v2.PermissionDecision.heartbeat:type_name -> criteria.v2.Heartbeat
	42, // 27: criteria.v2.InspectField.value:type_name -> google.protobuf.Value
	40, // 28: criteria.v2.InspectResponse.last_activity_at:type_name -> google.protobuf.Timestamp
	31, // 29: criteria.v2.InspectResponse.fields:type_name -> criteria.v2.InspectField
	41, // 30: criteria.v2.InspectResponse.extra:type_name -> google.protobuf.Struct
	2,  // 31: criteria.v2.AdapterSchemaProto.FieldsEntry.value:type_name -> criteria.v2.ConfigFieldProto
	4,  // 32: criteria.v2.AdapterService.Info:input_type -> criteria.v2.InfoRequest
	6,  // 33: criteria.v2.AdapterService.OpenSession:input_type -> criteria.v2.OpenSessionRequest
	10, // 34: criteria.v2.AdapterService.Execute:input_type -> criteria.v2.ExecuteRequest
	15, // 35: criteria.v2.AdapterService.Log:input_type -> criteria.v2.LogRequest
	19, // 36: criteria.v2.AdapterService.Permissions:input_type -> criteria.v2.PermissionEvent
	21, // 37: criteria.v2.AdapterService.Pause:input_type -> criteria.v2.PauseRequest
	23, // 38: criteria.v2.AdapterService.Resume:input_type -> criteria.v2.ResumeRequest
	25, // 39: criteria.v2.AdapterService.Snapshot:input_type -> criteria.v2.SnapshotRequest
	27, // 40: criteria.v2.AdapterService.Restore:input_type -> criteria.v2.RestoreRequest
	30, // 41: criteria.v2.AdapterService.Inspect:input_type -> criteria.v2.InspectRequest
	8,  // 42: criteria.v2.AdapterService.CloseSession:input_type -> criteria.v2.CloseSessionRequest
	5,  // 43: criteria.v2.AdapterService.Info:output_type -> criteria.v2.InfoResponse
	7,  // 44: criteria.v2.AdapterService.OpenSession:output_type -> criteria.v2.OpenSessionResponse
	14, // 45: criteria.v2.AdapterService.Execute:output_type -> criteria.v2.ExecuteEvent
	16, // 46: criteria.v2.AdapterService.Log:output_type -> criteria.v2.LogEvent
	20, // 47: criteria.v2.AdapterService.Permissions:output_type -> criteria.v2.PermissionDecision
	22, // 48: criteria.v2.AdapterService.Pause:output_type -> criteria.v2.PauseResponse
	24, // 49: criteria.v2.AdapterService.Resume:output_type -> criteria.v2.ResumeResponse
	26, // 50: criteria.v2.AdapterService.Snapshot:output_type -> criteria.v2.SnapshotResponse
	28, // 51: criteria.v2.AdapterService.Restore:output_type -> criteria.v2.RestoreResponse
	32, // 52: criteria.v2.AdapterService.Inspect:output_type -> criteria.v2.InspectResponse
	9,  // 53: criteria.v2.AdapterService.CloseSession:output_type -> criteria.v2.CloseSessionResponse
	43, // [43:54] is the sub-list for method output_type
	32, // [32:43] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_criteria_v2_adapter_proto_init() }
func file_criteria_v2_adapter_proto_init() {
	if File_criteria_v2_adapter_proto != nil {
		return
	}
	file_criteria_v2_options_proto_init()
	file_criteria_v2_adapter_proto_msgTypes[14].OneofWrappers = []any{
		(*ExecuteEvent_Adapter)(nil),
		(*ExecuteEvent_Tool)(nil),
		(*ExecuteEvent_Result)(nil),
		(*ExecuteEvent_Heartbeat)(nil),
	}
	file_criteria_v2_adapter_proto_msgTypes[19].OneofWrappers = []any{
		(*PermissionEvent_Request)(nil),
		(*PermissionEvent_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v2_adapter_proto_rawDesc), len(file_criteria_v2_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteria_v2_adapter_proto_goTypes,
		DependencyIndexes: file_criteria_v2_adapter_proto_depIdxs,
		MessageInfos:      file_criteria_v2_adapter_proto_msgTypes,
	}.Build()
	File_criteria_v2_adapter_proto = out.File
	file_criteria_v2_adapter_proto_goTypes = nil
	file_criteria_v2_adapter_proto_depIdxs = nil
}
