// Criteria v2 proto custom field options.
//
// Extension number 70000 is in the user-defined range (50000–99999), which is
// guaranteed never to be assigned by the Protobuf project. We claim 70000 for
// the criteria.sensitive annotation; neighbouring numbers (70001–70099) are
// reserved for future Criteria field options so forks cannot silently collide.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: criteria/v2/options.proto

package criteriav2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_criteria_v2_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70000,
		Name:          "criteria.v2.sensitive",
		Tag:           "varint,70000,opt,name=sensitive",
		Filename:      "criteria/v2/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// sensitive marks a field as carrying secret material.  The host's log
	// pipeline, the SDK's redaction-aware logger, and reflection-driven
	// debug/audit code all honor this annotation and either mask or refuse to
	// serialize the value.
	//
	// optional bool sensitive = 70000;
	E_Sensitive = &file_criteria_v2_options_proto_extTypes[0]
)

var File_criteria_v2_options_proto protoreflect.FileDescriptor

const file_criteria_v2_options_proto_rawDesc = "" +
	"\n" +
	"\x19criteria/v2/options.proto\x12\vcriteria.v2\x1a google/protobuf/descriptor.proto:=\n" +
	"\tsensitive\x12\x1d.google.protobuf.FieldOptions\x18\xf0\xa2\x04 \x01(\bR\tsensitiveB=Z;github.com/brokenbots/criteria/proto/criteria/v2;criteriav2b\x06proto3"

var file_criteria_v2_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_criteria_v2_options_proto_depIdxs = []int32{
	0, // 0: criteria.v2.sensitive:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_criteria_v2_options_proto_init() }
func file_criteria_v2_options_proto_init() {
	if File_criteria_v2_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteria_v2_options_proto_rawDesc), len(file_criteria_v2_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_criteria_v2_options_proto_goTypes,
		DependencyIndexes: file_criteria_v2_options_proto_depIdxs,
		ExtensionInfos:    file_criteria_v2_options_proto_extTypes,
	}.Build()
	File_criteria_v2_options_proto = out.File
	file_criteria_v2_options_proto_goTypes = nil
	file_criteria_v2_options_proto_depIdxs = nil
}
