#!/usr/bin/env bun
/**
 * Generate src/version.ts from package.json.
 *
 * SDK_VERSION is derived rather than hand-maintained so it cannot drift from the
 * published version (the release workflow stamps package.json from the git tag
 * before this runs, so both track the tag). The
 * output is a plain string literal, which stays inlineable when the SDK is
 * bundled into a compiled adapter — a runtime read of package.json would throw
 * inside `bun build --compile` output, where no package.json exists on disk.
 *
 * Runs as part of `bun run build`. Generated file is git-ignored.
 */
import pkg from '../package.json' with { type: 'json' };

const out = new URL('../src/version.ts', import.meta.url);
const body = `// GENERATED by scripts/gen-version.ts — do not edit. Source: package.json "version".
export const SDK_VERSION = ${JSON.stringify(pkg.version)};
`;
await Bun.write(out, body);
console.error(`wrote src/version.ts (SDK_VERSION=${pkg.version})`);
