// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=.js"
// @generated from file criteria/v1/adapter_plugin.proto (package criteria.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CloseSessionRequest, CloseSessionResponse, ExecuteEvent, ExecuteRequest, InfoRequest, InfoResponse, OpenSessionRequest, OpenSessionResponse, PermitRequest, PermitResponse } from "./adapter_plugin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AdapterPluginService defines the out-of-process adapter contract.
 *
 * @generated from service criteria.v1.AdapterPluginService
 */
export const AdapterPluginService = {
  typeName: "criteria.v1.AdapterPluginService",
  methods: {
    /**
     * @generated from rpc criteria.v1.AdapterPluginService.Info
     */
    info: {
      name: "Info",
      I: InfoRequest,
      O: InfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v1.AdapterPluginService.OpenSession
     */
    openSession: {
      name: "OpenSession",
      I: OpenSessionRequest,
      O: OpenSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v1.AdapterPluginService.Execute
     */
    execute: {
      name: "Execute",
      I: ExecuteRequest,
      O: ExecuteEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc criteria.v1.AdapterPluginService.Permit
     */
    permit: {
      name: "Permit",
      I: PermitRequest,
      O: PermitResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v1.AdapterPluginService.CloseSession
     */
    closeSession: {
      name: "CloseSession",
      I: CloseSessionRequest,
      O: CloseSessionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

