// CriteriaService — RPCs served by the server and consumed by Criteria agents.
//
// Authentication: all RPCs except `Register` require a token (Bearer header,
// `X-Criteria-Token` header, or `criteria-token` Connect metadata). Tokens are
// SHA-256 compared against `criteria.token_hash` in the orchestrator store.
//
// Caller ownership: mutating RPCs enforce that the authenticated caller owns
// the affected criteria agent or run. Implementations MUST enforce this contract.

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=.js"
// @generated from file criteria/v1/criteria.proto (package criteria.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Ack, ControlMessage, ControlSubscribeRequest, CreateRunRequest, HeartbeatRequest, HeartbeatResponse, ReattachRunRequest, ReattachRunResponse, RegisterRequest, RegisterResponse, ResumeRequest, ResumeResponse, Run } from "./criteria_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Envelope } from "./events_pb.js";

/**
 * @generated from service criteria.v1.CriteriaService
 */
export const CriteriaService = {
  typeName: "criteria.v1.CriteriaService",
  methods: {
    /**
     * Register enrolls a Criteria agent with the orchestrator. Returns the assigned
     * criteria id and an auth token the agent must present on all subsequent
     * RPCs.
     *
     * Bootstrap gate: implementations MUST require a bootstrap token (e.g. via
     * an `X-Server-Bootstrap` header) before accepting Register. When no
     * bootstrap mechanism is configured, implementations MUST return
     * Unimplemented. This prevents open self-registration in production.
     *
     * @generated from rpc criteria.v1.CriteriaService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Heartbeat advances the agent's `last_seen_at`. The orchestrator marks
     * agents offline whose heartbeat is older than a configurable threshold.
     *
     * The authenticated caller's identity is the canonical criteria agent being
     * updated. Implementations MUST ignore any request-supplied criteria_id and
     * use the caller's authenticated identity instead.
     *
     * @generated from rpc criteria.v1.CriteriaService.Heartbeat
     */
    heartbeat: {
      name: "Heartbeat",
      I: HeartbeatRequest,
      O: HeartbeatResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateRun mints a new run owned by the authenticated caller. The
     * orchestrator is the sole source of run ids.
     *
     * The run is always recorded under the authenticated caller's criteria ID.
     * The request's `criteria_id` field is informational only. Implementations
     * MUST ignore any request-supplied criteria_id and use the caller's
     * authenticated identity.
     *
     * @generated from rpc criteria.v1.CriteriaService.CreateRun
     */
    createRun: {
      name: "CreateRun",
      I: CreateRunRequest,
      O: Run,
      kind: MethodKind.Unary,
    },
    /**
     * ReattachRun lets a Criteria agent query the orchestrator about an in-flight run
     * after a crash or restart. The orchestrator returns the current status,
     * last active step, and whether the agent may resume execution.
     *
     * Implementations MUST reject the request with PERMISSION_DENIED if the
     * authenticated caller does not own the target run's criteria agent.
     *
     * @generated from rpc criteria.v1.CriteriaService.ReattachRun
     */
    reattachRun: {
      name: "ReattachRun",
      I: ReattachRunRequest,
      O: ReattachRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Resume delivers a named signal (or an approval decision) to a paused run.
     *
     * Implementations MUST reject the request with PERMISSION_DENIED if the
     * authenticated caller does not own the target run's criteria agent.
     *
     * This RPC is SDK contract surface: field names, payload semantics, and
     * error-reason strings are stable for third-party orchestrators.
     *
     * @generated from rpc criteria.v1.CriteriaService.Resume
     */
    resume: {
      name: "Resume",
      I: ResumeRequest,
      O: ResumeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SubmitEvents is a bidirectional stream. The client writes Envelopes and
     * the server replies with an Ack per persisted envelope (run_id, seq,
     * correlation_id). On reconnect the client may include `since_seq` in
     * request metadata to request replay of events that were persisted but not
     * yet acknowledged.
     *
     * Implementations MUST verify on every envelope that the authenticated caller
     * owns the envelope's run_id. On the first violation the stream MUST be
     * rejected with PERMISSION_DENIED; envelopes MUST NOT be silently dropped.
     *
     * @generated from rpc criteria.v1.CriteriaService.SubmitEvents
     */
    submitEvents: {
      name: "SubmitEvents",
      I: Envelope,
      O: Ack,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * Control is a long-lived server-stream that the orchestrator uses to push
     * commands to a connected Criteria agent (cancel a run, send a prompt to an
     * agent, ...).
     *
     * The authenticated caller's identity determines the registry key for the
     * Control subscription. Implementations MUST ignore any request-supplied
     * criteria_id and use the caller's authenticated identity.
     *
     * @generated from rpc criteria.v1.CriteriaService.Control
     */
    control: {
      name: "Control",
      I: ControlSubscribeRequest,
      O: ControlMessage,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

