// ServerService — read/control RPCs served by the server and consumed by UI clients
// (and any human tooling such as grpcurl).

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=.js"
// @generated from file criteria/v1/server.proto (package criteria.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Agent, GetAgentRequest, GetRunRequest, InspectRunRequest, InspectRunResponse, ListAgentsRequest, ListAgentsResponse, ListRunEventsRequest, ListRunEventsResponse, ListRunsRequest, ListRunsResponse, PauseRunRequest, PauseRunResponse, ResumeRunRequest, ResumeRunResponse, SendPromptRequest, SendPromptResponse, StopRunRequest, StopRunResponse, WatchRunRequest } from "./server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Run } from "./criteria_pb.js";
import { Envelope } from "./events_pb.js";

/**
 * @generated from service criteria.v1.ServerService
 */
export const ServerService = {
  typeName: "criteria.v1.ServerService",
  methods: {
    /**
     * @generated from rpc criteria.v1.ServerService.ListAgents
     */
    listAgents: {
      name: "ListAgents",
      I: ListAgentsRequest,
      O: ListAgentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v1.ServerService.GetAgent
     */
    getAgent: {
      name: "GetAgent",
      I: GetAgentRequest,
      O: Agent,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v1.ServerService.ListRuns
     */
    listRuns: {
      name: "ListRuns",
      I: ListRunsRequest,
      O: ListRunsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v1.ServerService.GetRun
     */
    getRun: {
      name: "GetRun",
      I: GetRunRequest,
      O: Run,
      kind: MethodKind.Unary,
    },
    /**
     * ListRunEvents replaces the Phase 0 run-events HTTP endpoint.
     *
     * @generated from rpc criteria.v1.ServerService.ListRunEvents
     */
    listRunEvents: {
      name: "ListRunEvents",
      I: ListRunEventsRequest,
      O: ListRunEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * WatchRun replaces the Phase 0 run-stream endpoint. Emits any already
     * persisted events (since `since_seq`) and then tails live events until the
     * client disconnects or the run reaches a terminal state.
     *
     * @generated from rpc criteria.v1.ServerService.WatchRun
     */
    watchRun: {
      name: "WatchRun",
      I: WatchRunRequest,
      O: Envelope,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * StopRun cancels a run. If an agent is attached to the run via its
     * Control stream, the orchestrator pushes a RunCancel to it. Returns
     * FAILED_PRECONDITION if the agent is not connected.
     *
     * Implementations MUST reject the request with PERMISSION_DENIED if the
     * authenticated caller does not own the target run's agent.
     *
     * @generated from rpc criteria.v1.ServerService.StopRun
     */
    stopRun: {
      name: "StopRun",
      I: StopRunRequest,
      O: StopRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * PauseRun halts a run without losing state. The adapter session is
     * paused via the v2 adapter Pause RPC.
     *
     * @generated from rpc criteria.v1.ServerService.PauseRun
     */
    pauseRun: {
      name: "PauseRun",
      I: PauseRunRequest,
      O: PauseRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ResumeRun continues a previously paused run.
     *
     * @generated from rpc criteria.v1.ServerService.ResumeRun
     */
    resumeRun: {
      name: "ResumeRun",
      I: ResumeRunRequest,
      O: ResumeRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * InspectRun returns structured read-only state for a run. If session_id
     * is empty the server may return a summary across all sessions.
     *
     * @generated from rpc criteria.v1.ServerService.InspectRun
     */
    inspectRun: {
      name: "InspectRun",
      I: InspectRunRequest,
      O: InspectRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SendPrompt — schema-only stub for Phase 2.3. UI clients can wire up
     * against this method, but the server currently returns UNIMPLEMENTED.
     *
     * @generated from rpc criteria.v1.ServerService.SendPrompt
     */
    sendPrompt: {
      name: "SendPrompt",
      I: SendPromptRequest,
      O: SendPromptResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

