// Criteria Adapter Protocol v2.
//
// WS03 cutover: criteria/v1/adapter_plugin.proto was deleted; this file is
// now the sole wire contract for all adapter binaries (copilot, mcp, noop,
// shell-builtin, and third-party adapters). Any adapter previously built
// against v1 must be recompiled against these bindings.
//
// The Permissions RPC is a bidirectional stream: the HOST (gRPC client) sends
// PermissionEvent messages (request=allow, cancel=deny) and the ADAPTER (gRPC
// server) sends PermissionDecision acknowledgments back. Adapters that embed
// sdk/adapterhost.UnimplementedPermissions receive post-hoc enforcement
// (outcome override to needs_review on denial); adapters that implement
// Permissions themselves (e.g. copilot) get blocking enforcement so the tool
// never runs when denied.
//
// See docs/adapters.md for the feature roadmap and well-known event_kind registry.

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=.js"
// @generated from file criteria/v2/adapter.proto (package criteria.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CloseSessionRequest, CloseSessionResponse, ExecuteEvent, ExecuteRequest, InfoRequest, InfoResponse, InspectRequest, InspectResponse, LogEvent, LogRequest, OpenSessionRequest, OpenSessionResponse, PauseRequest, PauseResponse, PermissionDecision, PermissionEvent, RestoreRequest, RestoreResponse, ResumeRequest, ResumeResponse, SnapshotRequest, SnapshotResponse } from "./adapter_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AdapterService is the out-of-process adapter contract for Criteria v2.
 *
 * @generated from service criteria.v2.AdapterService
 */
export const AdapterService = {
  typeName: "criteria.v2.AdapterService",
  methods: {
    /**
     * @generated from rpc criteria.v2.AdapterService.Info
     */
    info: {
      name: "Info",
      I: InfoRequest,
      O: InfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.OpenSession
     */
    openSession: {
      name: "OpenSession",
      I: OpenSessionRequest,
      O: OpenSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Execute
     */
    execute: {
      name: "Execute",
      I: ExecuteRequest,
      O: ExecuteEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Log
     */
    log: {
      name: "Log",
      I: LogRequest,
      O: LogEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Permissions
     */
    permissions: {
      name: "Permissions",
      I: PermissionEvent,
      O: PermissionDecision,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Pause
     */
    pause: {
      name: "Pause",
      I: PauseRequest,
      O: PauseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Resume
     */
    resume: {
      name: "Resume",
      I: ResumeRequest,
      O: ResumeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Snapshot
     */
    snapshot: {
      name: "Snapshot",
      I: SnapshotRequest,
      O: SnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Restore
     */
    restore: {
      name: "Restore",
      I: RestoreRequest,
      O: RestoreResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.Inspect
     */
    inspect: {
      name: "Inspect",
      I: InspectRequest,
      O: InspectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc criteria.v2.AdapterService.CloseSession
     */
    closeSession: {
      name: "CloseSession",
      I: CloseSessionRequest,
      O: CloseSessionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

