// Criteria v2 proto custom field options.
//
// Extension number 70000 is in the user-defined range (50000–99999), which is
// guaranteed never to be assigned by the Protobuf project. We claim 70000 for
// the criteria.sensitive annotation; neighbouring numbers (70001–70099) are
// reserved for future Criteria field options so forks cannot silently collide.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.js"
// @generated from file criteria/v2/options.proto (package criteria.v2, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file criteria/v2/options.proto.
 */
export const file_criteria_v2_options: GenFile = /*@__PURE__*/
  fileDesc("Chljcml0ZXJpYS92Mi9vcHRpb25zLnByb3RvEgtjcml0ZXJpYS52Mjo9CglzZW5zaXRpdmUSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGPCiBCABKAhSCXNlbnNpdGl2ZUKqAQoPY29tLmNyaXRlcmlhLnYyQgxPcHRpb25zUHJvdG9QAVo8Z2l0aHViLmNvbS9icm9rZW5ib3RzL2NyaXRlcmlhL3Nkay9wYi9jcml0ZXJpYS92MTtjcml0ZXJpYXYxogIDQ1hYqgILQ3JpdGVyaWEuVjLKAgtDcml0ZXJpYVxWMuICF0NyaXRlcmlhXFYyXEdQQk1ldGFkYXRh6gIMQ3JpdGVyaWE6OlYyYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * sensitive marks a field as carrying secret material.  The host's log
 * pipeline, the SDK's redaction-aware logger, and reflection-driven
 * debug/audit code all honor this annotation and either mask or refuse to
 * serialize the value.
 *
 * @generated from extension: bool sensitive = 70000;
 */
export const sensitive: GenExtension<FieldOptions, boolean> = /*@__PURE__*/
  extDesc(file_criteria_v2_options, 0);

